Index-html/css edit
YunaSuzuki/chat-space pull request #6
Opened 2019-04-07 03:42 UTC by YunaSuzuki

Html, scss編集

2019-04-07 03:44 UTC, hiroki5123 commented
何をしたのかがわからないので、WHATとWHYを書いて、ビューファイルを作成した場合は画面のキャプチャをこちらに添付してください。

2019-04-07 03:47 UTC, YunaSuzuki commented
chatspaceのメイン画面の実装を行いました(html/css)
<img width="1003" alt="スクリーンショット 2019-04-07 12 46 51" src="https://user-images.githubusercontent.com/47857479/55678365-46f24f00-5933-11e9-9bb3-d762d328cf14.png">

2019-04-07 03:58 UTC, ghost requested changes

2019-04-07 03:58 UTC, hiroki5123 commented on app/assets/stylesheets/messages.scss
> +    height: 40px;
インデントずれています

2019-04-07 03:58 UTC, hiroki5123 commented on app/views/messages/index.html.erb
> +<html>
hamlで書かないんですか？

2019-04-07 04:10 UTC, YunaSuzuki commented on app/assets/stylesheets/messages.scss
> +    height: 40px;
修正しました。

2019-04-07 04:12 UTC, YunaSuzuki commented on app/views/messages/index.html.erb
> +<html>
hamlでコードを書いた事がなく、htmlの方がどちらかといえば慣れているので、htmlの方で書きました。。

2019-04-07 04:53 UTC, hiroki5123 commented on app/views/messages/index.html.erb
> +<html>
カリキュラムではhamlで書くよう、指定があったかと思いますのでHamlで書いていただきますよう、お願い致します。

2019-04-07 05:37 UTC, YunaSuzuki commented on app/views/messages/index.html.erb
> +<html>
index.html.erbからhamlへ変換しました。

2019-04-07 05:39 UTC, ghost requested changes

2019-04-07 05:39 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +  %body
ここから上は削除してください

2019-04-07 05:39 UTC, ghost requested changes

2019-04-07 05:39 UTC, hiroki5123 commented on app/assets/stylesheets/messages.scss
> +
空行が多いです

2019-04-07 05:39 UTC, hiroki5123 commented on app/views/messages/index.html.erb
> +<html>
こちらのファイルは使わないので、削除してください

2019-04-07 05:40 UTC, ghost requested changes

2019-04-07 05:40 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +            %ul.side-header__box__menu
ulの直下の要素はliである必要がありますので、修正をお願い致します

2019-04-07 05:42 UTC, YunaSuzuki commented on app/assets/stylesheets/messages.scss
> +
修正しました。

2019-04-07 05:43 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +  %body
すみません、何行目から上でしょうか。。

2019-04-07 05:46 UTC, YunaSuzuki commented on app/views/messages/index.html.erb
> +<html>
削除しました

2019-04-07 05:48 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +            %ul.side-header__box__menu
liに修正しました。

2019-04-07 06:06 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +  %body
削除しました。

2019-04-07 06:38 UTC, ghost requested changes

2019-04-07 06:38 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +%body
ここから上は削除してください。

2019-04-07 06:38 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +        .chat-side
エディタを変えたのかエディタの設定を変えたのかわかりませんが、インデントのスペースの数が変わっているので、tab一個分(半角スペース二個分)に全て修正してください。

2019-04-07 06:39 UTC, ghost requested changes

2019-04-07 06:39 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +                        %i.fa.fa-edit
ulの直下の要素はli要素である必要がありますので、修正をお願い致します

2019-04-07 06:41 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +                        %i.fa.fa-edit
修正できていませんでした。申し訳ありません。
修正しました。

2019-04-07 06:46 UTC, ghost requested changes
インデントも修正できてないので、もう一度修正をお願い致します。

2019-04-07 06:46 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +%body
ここから上は削除してください。
なんのために残しているのでしょうか・・・？

2019-04-07 06:54 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +        .chat-side
修正しました。

2019-04-07 06:55 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +%body
この部分を削除すると、fontawesomeなど適用されないのですが。。

2019-04-07 07:11 UTC, hiroki5123 commented
fontawesomeはgemを入れて、そちらをimportする形式にしてください。
よろしくお願い致します。

2019-04-07 20:13 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +%body
gemを入れてapplicaion.scssにインポートする形に修正しました。

2019-04-08 02:00 UTC, miyagit commented on app/views/messages/index.html.haml
> +            %input.form__new-message__input-box__text{:name => "message[content]", :placeholder => "type a message", :type => "text"}/
ハッシュロケットで書いているところはすべて直しましょう。

2019-04-08 02:45 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +            %input.form__new-message__input-box__text{:name => "message[content]", :placeholder => "type a message", :type => "text"}/
"data-disable-with" => "Send"の部分も別の記法で書き直すのでしょうか。

2019-04-08 02:49 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +          %input.form__new-message__submit-btn{"data-disable-with" => "Send", name: "commit", type: "submit", value: "Send"}/
"data-disable-with": "Send"
ではいかかでしょうか？

2019-04-08 02:50 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +%body
こちらのbodyタグも消してください。

2019-04-08 02:51 UTC, kuroko918 commented
https://github.com/YunaSuzuki/chat-space/pull/6#discussion_r272871973
こちらもお願いいたします。

2019-04-08 02:53 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +          %input.form__new-message__submit-btn{"data-disable-with" => "Send", name: "commit", type: "submit", value: "Send"}/
その書き方を試してみたのですが、コロンに色が着いてしまうのですが、大丈夫でしょうか。。
他の部分では色は特についていないのですが。。

2019-04-08 02:56 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +%body
修正しました。

2019-04-08 03:02 UTC, miyagit commented on app/views/messages/index.html.haml
> +          %li.fa.fa-edit
fontawesomeのgemは既に入れられているみたいなのでヘルパーメソッドを使いましょう。

2019-04-08 03:28 UTC, YunaSuzuki commented on app/views/messages/index.html.haml
> +          %li.fa.fa-edit
修正しました。

2019-04-08 03:35 UTC, kuroko918 commented on app/views/messages/index.html.haml
> +          %input.form__new-message__submit-btn{"data-disable-with" => "Send", name: "commit", type: "submit", value: "Send"}/
そちらで大丈夫かと思います。

2019-04-08 03:36 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-04-08 03:39 UTC, merged